config/routes.rb
Rails.application.routes.draw do
  get "tracks/index"
  get "tracks/new"
  get "tracks/create"
  get "tracks/update"
  get "tracks/edit"
  get "tracks/delete"
  get "daily_tasks/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # Auth:
  root "auth#log_in"
  get "auth/sign_up"
  post "auth/sign_user_up", as: "sign_user_up"
  post "auth/log_user_in", as: "log_user_in"
  get "dashboard/home"
  get "dashboard/new_goal"
  post "dashboard/create_goal"
  # Resources:
  resources :workouts do
    post "add_lift_form", on: :collection, as: :add_lift_form
    delete "delete_lift_form", on: :collection, as: :delete_lift_form
    get "list", on: :collection
    post "add_lift_to_workout", on: :member
  end
  resources :daily_tasks do
    post "add_task", on: :collection, as: :add_task
    post "add_task_to_box", on: :collection, as: :add_task_to_box
    patch "complete", on: :member, as: :complete
  end
  resources :sagas, only: [ :index, :new, :create, :show, :edit, :update, :destroy ]
  resources :smart_goals do
    patch "complete", on: :member, as: :complete
  end
  resources :tracks
end

app/models/daily_task.rb
class DailyTask < ApplicationRecord
  belongs_to :smart_goal
  enum :priority, [ :is_urgent_and_important, :is_urgent_and_not_important, :is_not_urgent_and_important, :is_not_urgent_and_not_important ]
  validates :title, length: { minimum: 1, message: "Title must have at least one char" }
  validates :priority, presence: { message: "Must have a priority" }
  validates :smart_goal, presence: { message: "Must have a smart goal" }

  def goal_title
    smart_goal.measurable_goal
  end
end

app/controllers/daily_tasks_controller.rb
class DailyTasksController < ApplicationController
  include Authentication
  include DailyTasksHelper
  before_action :check_logged_in

  def index
    session[:page_type] = "daily_tasks"
    @user = User.find(session[:user_id])
    @daily_tasks = @user.daily_tasks.where(is_completed: false)
  end

  def add_task_to_box
    user = User.find(session[:user_id])
    @priority = params[:priority]
    @daily_tasks = user.daily_tasks.where(priority: DailyTask.priorities[@priority.to_sym], is_completed: false)
    @smart_goals = user.smart_goals
  end

  def create
    @user = User.find(session[:user_id])
    @daily_task = DailyTask.create(daily_task_params)
    @errors = format_errors(@daily_task.errors)
    @priority = daily_task_params[:priority]
    @daily_tasks = @user.daily_tasks.where(is_completed: false, priority: DailyTask.priorities[@priority.to_sym])
  end

  def destroy
    @user = User.find(session[:user_id])
    @priority = params[:priority]
    @daily_task = DailyTask.find(params[:id])
    @daily_task.destroy
    @daily_tasks = @user.daily_tasks.where(is_completed: false, priority: DailyTask.priorities[@priority.to_sym])
  end

  def update
    @user = User.find(session[:user_id])
    @daily_task = DailyTask.find(params[:id])
    @daily_task.update(daily_task_params)
    redirect_to daily_tasks_path
  end

  def add_task
    daily_task = DailyTask.create(daily_task_params)
  end

  def complete
    user = User.find(session[:user_id])
    @daily_task = DailyTask.find(params[:id])
    @daily_task.update(is_completed: true)
    @priority = params[:priority]
    puts @priority
    @daily_tasks = user.daily_tasks.where(is_completed: false, priority: DailyTask.priorities[@priority.to_sym])
  end

  private

  def daily_task_params
    params.require(:daily_task).permit(:smart_goal_id, :title, :priority)
  end
end

app/helpers/daily_tasks_helper.rb
module DailyTasksHelper
  def humanize_priorities
    priorities = []
    DailyTask.priorities.each do |prio|
      prio_arr = []
      prio_arr << prio[0].humanize
      prio_arr << prio[0]
      priorities << prio_arr
    end

    priorities
  end
end

app/views/daily_tasks/_edit_single_task_modal.html.erb
<div id="<%= dom_id(daily_task) %>_modal" class="modal">
  <div class="modal-background"></div>
  <div class="modal-content">
    <div class="box animate__animated animate__fadeIn">
      <div class="is-flex is-flex-direction-column">
        <h2 class="barlow-condensed-semibold is-size-4">Edit <%= daily_task.title  %></h2>
        <div>
          <%= form_with model: daily_task, data: { turbo_method: :patch }, class: "form" do |form| %>
            <div class="field">
              <%= form.label :title %>
              <%= form.text_field :title, class: "input" %>
            </div>

            <div class="field">
              <div class="select">
                <%= form.select :priority, options_for_select(humanize_priorities) %>
              </div>
            </div>

            <div class="field">
              <div class="select">
                <%= form.select :smart_goal_id, options_from_collection_for_select(user.smart_goals, :id, :measurable_goal) %>
              </div>
            </div>

            <%= form.submit "Update", class: "button is-primary" %>
          <% end %>
        </div>
      </div>

      <!-- Your content -->
    </div>
  </div>

  <button class="modal-close is-large" aria-label="close"></button>
</div>

app/views/daily_tasks/_no_tasks.html.erb
<div class="is-flex h-100">
  <span class="mx-auto my-auto is-size-5 montserrat-600">No tasks found.</span>
</div>

app/views/daily_tasks/_task_boxes.html.erb
<% DailyTask.priorities.keys.each do |priority| %>
  <div class="cell box bulma-huge-box">
      <div class="block is-flex">
        <h2 class="barlow-condensed-semibold is-size-3"><%= priority.to_s.humanize %></h2>
        <%= link_to add_task_to_box_daily_tasks_path(priority: priority), data: { "turbo_method": "post" }, class: "button is-primary ml-auto" do %>
            <i class="fa-solid fa-plus"></i>
        <% end %>
      </div>
      <%= turbo_frame_tag priority do %>
        <% if tasks.present? %>
            <%= render partial: "task_list", locals: { tasks: DailyTask.where(priority: priority), user: user } %>
          <% else %>
            <%= render partial: "no_tasks" %>
          <% end %>
      <% end %>
  </div>
<% end %>

app/views/daily_tasks/_task_list.html.erb
<% tasks.each do |daily_task| %>
  <div class="block">
    <%= turbo_frame_tag dom_id(daily_task) do %>
      <div class="grid">
        <div class="cell">
          <span><%= daily_task.title %></span>
        </div>
        <div class="cell">
          <span><%= daily_task.smart_goal.measurable_goal %></span>
        </div>
        <div class="cell">
          <%= link_to complete_daily_task_path(daily_task.id, priority: daily_task.priority), data: { turbo_method: "patch" }, class: "button is-primary" do %>
            <i class="fa-solid fa-check"></i>
          <% end %>
          <%= link_to daily_task_path(daily_task.id, priority: daily_task.priority), data: { turbo_method: :delete }, class: "button is-danger" do %>
            <i class="fa-solid fa-trash"></i>
          <% end %>
          <button type="button" class="button is-warning" onclick="openModal(document.getElementById('<%= dom_id(daily_task) %>_modal'));">
            <i class="fa-solid fa-pencil"></i>
          </button>
        </div>
      </div>
    <% end %>
  </div>
  <%= render partial: "edit_single_task_modal", locals: { daily_task: daily_task, user: user } %>
<% end %>

app/views/daily_tasks/add_task_to_box.turbo_stream.erb
<% if @daily_tasks.count.zero? %>
  <%= turbo_stream.update @priority %>
<% end %>
<%= turbo_stream.append @priority do %>
  <%= turbo_frame_tag dom_id(DailyTask.new) do %>
    <%= form_with model: DailyTask.new, class: "mt-5" do |form| %>
      <%= form.hidden_field :priority, value: @priority %>
      <div class="grid">
        <div class="cell">
          <%= form.text_field :title, class: "input" %>
        </div>
        <div class="cell">
          <div class="select">
            <%= form.select :smart_goal_id, options_from_collection_for_select(@smart_goals, :id, :measurable_goal) %>
          </div>
        </div>
        <div class="cell">
          <%= form.submit "Save", class: "button is-warning montserrat-500" %>
        </div>
      </div>
      <%= render partial: "layouts/error_messages", locals: { messages: @errors } %>
    <% end %>
  <% end %>
<% end %>

app/views/daily_tasks/complete.turbo_stream.erb
<%= turbo_stream.remove @daily_task %>
<% unless @daily_tasks.count > 0 %>
  <%= turbo_stream.update @priority do %>
    <%= render partial: "no_tasks" %>
  <% end %>
<% end %>

app/views/daily_tasks/create.turbo_stream.erb
<% if @errors.present? %>
  <%= turbo_stream.replace("err_messages") do %>
    <%= render partial: "layouts/error_messages", locals: { messages: @errors } %>
  <% end %>
<% else %>
  <%= turbo_stream.replace("err_messages") do %>
    <%= render partial: "layouts/error_messages", locals: { messages: [] } %>
  <% end %>
  <%= turbo_stream.update @priority do %>
    <%= render partial: 'daily_tasks/task_list', locals: { tasks: @daily_tasks, user: @user } %>
  <% end %>
  <%= turbo_stream.remove DailyTask.new %>
<% end %>

app/views/daily_tasks/destroy.turbo_stream.erb
<%= turbo_stream.remove @daily_task %>
<% unless @daily_tasks.count > 0 %>
  <%= turbo_stream.update @priority do %>
    <%= render partial: "no_tasks" %>
  <% end %>
<% end %>

app/views/daily_tasks/index.html.erb
<%= turbo_page_requires_reload %>
<section class="hero is-small">
  <div class="hero-body">
    <h1 class="barlow-condensed-bold is-size-2">Hey, <span class="has-text-primary"><%= @user.first_name %></span>!</h1>
    <span class="subtitle">Here's your <span class="has-text-warning">tasks</span> for today:</span>
  </div>
  <div class="section">
    <div class="fixed-grid">
      <div class="grid">
        <!-- Turning this into a partial -->
        <%= render partial: "task_boxes", locals: { tasks: @daily_tasks, user: @user } %>
      </div>
    </div>
  </div>
</section>

app/views/daily_tasks/new.html.erb
<section class="hero is-small">
  <div class="hero-body">
    <h1 class="barlow-condensed-bold is-size-3">Add <span class="has-text-primary">Daily Task(s):</span></h1>
  </div>
</section>


<% if @smart_goals.present? %>
  <%= turbo_frame_tag "user_tasks" do %>
    <% if @tasks.present? %>
      <% @tasks.each do |task| %>
        <%= render partial: "task_list", locals: { daily_task: task, user: @user } %>
      <% end %>
    <% end %>
  <% end %>
<% end %>
<section class="section">
  <%= form_with model: @daily_task, class: "form" do |f| %>
    <div class="block">
      <% if @smart_goals.present? %>
        <div class="select">
          <%= f.select :smart_goal_id, options_from_collection_for_select(@smart_goals, :id, :measurable_goal) %>
        </div>
      <% end %>
      <div class="select">
        <%= f.select :priority, options_for_select(@priorities) %>
      </div>
    </div>
    <div class="field">
      <%= f.label :title, class: "label" %>
      <%= f.text_field :title, class: "input" %>
    </div>

    <%= f.submit "Save", class: "button is-primary" %>
  <% end %>
</section>

<%= render partial: "layouts/error_messages", locals: { messages: [] } %>