config/routes.rb
Rails.application.routes.draw do
  get "tracks/index"
  get "tracks/new"
  get "tracks/create"
  get "tracks/update"
  get "tracks/edit"
  get "tracks/delete"
  get "daily_tasks/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # Auth:
  root "auth#log_in"
  get "auth/sign_up"
  post "auth/sign_user_up", as: "sign_user_up"
  post "auth/log_user_in", as: "log_user_in"
  get "dashboard/home"
  get "dashboard/new_goal"
  post "dashboard/create_goal"
  # Resources:
  resources :workouts do
    post "add_lift_form", on: :collection, as: :add_lift_form
    delete "delete_lift_form", on: :collection, as: :delete_lift_form
    get "list", on: :collection
    post "add_lift_to_workout", on: :member
  end
  resources :daily_tasks do
    post "add_task", on: :collection, as: :add_task
    post "add_task_to_box", on: :collection, as: :add_task_to_box
    patch "complete", on: :member, as: :complete
  end
  resources :sagas, only: [ :index, :new, :create, :show, :edit, :update, :destroy ]
  resources :smart_goals do
    patch "complete", on: :member, as: :complete
  end
  resources :tracks
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  include Authentication
  include ErrorHandling
  include DashboardHelper
  include GeneralViewHelper
  before_action :check_logged_in
  def home
    session[:page_type] = "dashboard"
    @user = User.find(session[:user_id])
    @saga = @user.sagas.last
    @tracks = @user.tracks.includes(:smart_goals)
    @smart_goals = SmartGoal.where(track: @tracks)
    @daily_tasks = @user.daily_tasks.where(is_completed: false)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_fitness_tracking_javascript.html.erb
<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', () => {
        // Functions to open and close a modal
        function openModal($el) {
            $el.classList.add('is-active');
        }

        function closeModal($el) {
            $el.classList.remove('is-active');
        }

        function closeAllModals() {
            (document.querySelectorAll('.modal') || []).forEach(($modal) => {
                closeModal($modal);
            });
        }

        // Add a click event on buttons to open a specific modal
        (document.querySelectorAll('.js-modal-trigger') || []).forEach(($trigger) => {
            const modal = $trigger.dataset.target;
            const $target = document.getElementById(modal);

            $trigger.addEventListener('click', () => {
                openModal($target);
            });
        });

        // Add a click event on various child elements to close the parent modal
        (document.querySelectorAll('.modal-background, .modal-close, .modal-card-head .delete, .modal-card-foot .button') || []).forEach(($close) => {
            const $target = $close.closest('.modal');

            $close.addEventListener('click', () => {
                closeModal($target);
            });
        });

        // Add a keyboard event to close all modals
        document.addEventListener('keydown', (event) => {
            if(event.key === "Escape") {
                closeAllModals();
            }
        });
    });
    function openModal(modalId) {
        let element = document.getElementById(modalId);
        element.classList.add("is-active");
    }
    function addLift(e) {
      e.preventDefault();
      openModal("add-lift-modal");
    }
</script>

app/views/dashboard/create_goal.turbo_stream.erb
<% if @errors.present? %>
  <%= turbo_stream.replace("err_messages") do %>
    <%= render partial: "layouts/error_messages", locals: { messages: @errors } %>
  <% end %>
<% else %>
  <%= turbo_stream.remove "err_messages" %>
  <%= turbo_stream.replace("new_goal_frame") do %>
    <%= render partial: 'layouts/success_message', locals: { message: "Goal successfully created!" } %>
  <% end %>
<% end %>

app/views/dashboard/fitness_tracking.html.erb
<%= render partial: "fitness_tracking_javascript" %>
<section class="hero">
  <div class="hero-body">
    <h1 class="title">Welcome to your fitness dashboard, <span class="has-text-primary"><%= @user.name.split(" ")[0] %></span></h1>
  </div>
</section>
<div class="section">
  <span class="is-size-4">Progress:</span>
  <progress class="progress is-primary" value="0" max="100"></progress>
  <span class="is-size-4">Total: <span class="has-text-primary has-text-weight-bold"><%= @user.workouts.count %> workouts</span>.</span>
  <br>
  <span class="is-size-4">Current streak: <span class="has-text-weight-bold has-text-warning"><%= @user.workout_streak %> days</span>.</span>
  <br>
</div>
<div class="section">
  <div class="grid">
    <div class="cell">
      <div class="box">
        <h3 class="title is-size-5">Current Reps:</h3>
        <div class="is-flex is-flex-direction-column">
          <span>Dumbbell Bench: 65</span>
          <span>Deadlift: 265</span>
          <span>Squat: 145</span>
        </div>
      </div>
    </div>
    <div class="cell">
      <div class="box">
        <h3 class="title is-size-5">Diet:</h3>
        <div class="is-flex is-flex-direction-column">
          <span>Lorem ipsum...</span>
          <span>To be</span>
          <span>Implemented in the future</span>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="section">
  <%= link_to "Add a workout", dashboard_new_workout_path, class: "button is-primary" %>
  <%= link_to "Log Food", "#", class: "button is-light" %>
</div>

app/views/dashboard/home.html.erb
<%= turbo_page_requires_reload %>
<section class="hero is-small">
  <div class="hero-body">
    <h1 class="is-size-2 barlow-condensed-bold">Welcome, <span class="has-text-primary"><%= @user.first_name %>!</span></h1>
    <span class="subtitle">This is your personal page. From here, you can monitor <span class="has-text-primary has-text-weight-bold">sagas</span>, <span class="has-text-danger has-text-weight-bold">goals</span>, and <span class="has-text-warning has-text-weight-bold">tasks.</span></span>
  </div>
</section>

<% if @saga.present? %>
  <div class="section">
    <div class="grid">
      <div class="cell">
        <div class="box bulma-custom-box">
          <div class="is-flex is-flex-direction-column h-100">
            <h2 class="is-size-4 barlow-condensed-semibold">Current saga: <span class="has-text-danger"><%= @saga.title %></span></h2>
            <div class="block">
              <span class="is-size-6">Progress:</span>
              <progress class="progress is-danger" value="<%= @saga.progress %>" max="<%= @saga.len %>"></progress>
            </div>
            <div class="is-flex is-flex-direction-column block">
              <span>Start date: <span class="has-text-weight-bold"><%= format_date(@saga.start_date) %></span></span>
              <span>End date: <span class="has-text-weight-bold"><%= format_date(@saga.end_date) %></span></span>
              <span>Remaining days: <span class="has-text-weight-bold"><%= days_remaining(@saga.start_date, @saga.end_date) %></span></span>
            </div>
            <div class="buttons mt-auto">
              <%= link_to "View", saga_path(@saga.id), class: "button is-primary" %>
              <%= link_to "Edit", edit_saga_path(@saga.id), class: "button is-warning" %>
            </div>
          </div>
        </div>
      </div>

      <div class="cell">
        <div class="box bulma-custom-box">
          <div class="is-flex is-flex-direction-column h-100">
              <% if @tracks.present? %>
                <div class="block">
                  <h2 class="is-size-4 barlow-condensed-semibold">Goals:</h2>
                </div>
              <ul>
                <% @tracks.each do |track| %>
                  <li class="is-flex is-flex-direction-column block">
                    <span class="is-size-5 barlow-condensed-semibold"><%= track.title %></span>
                    <% if @smart_goals.where(track: track).count > 0 %>
                      <% @smart_goals.where(track: track).each do |goal| %>
                        <div class="block">
                          <div class="is-flex is-flex-direction-column">
                            <div class="content">
                              <ul>
                                <li>
                                  <div class="grid my-1">
                                    <div class="cell">
                                      <span class="has-text-weight-bold"><%= goal.measurable_goal %></span>
                                    </div>
                                    <div class="cell is-flex is-align-items-center">
                                      <span class="has-text-weight-bold">Progress: </span>
                                      <progress class="progress is-danger ml-4" max=100 value=0></progress>
                                    </div>
                                  </div>
                                  <div class="is-flex is-flex-direction-column">
                                    <span class="">Start date: <span class="has-text-weight-bold"><%= format_date(goal.start_date) %></span></span>
                                    <span>End date: <span class="has-text-weight-bold"><%= format_date(goal.end_date) %></span></span>
                                  </div>
                                </li>
                              </ul>
                            </div>
                          </div>
                        </div>
                      <% end %>
                    <% else %>
                      <span class="is-size-6">No goals for this track.</span>
                    <% end %>
                  </li>
                <% end %>
              </ul>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <section class="section">
    <div class="block">
      <h3 class="barlow-condensed-semibold is-size-3">Daily tasks:</h3>
    </div>
    <% if @user.daily_tasks.present? %>
      <div>
        <div class="block">
          <p class="is-size-4">You have <span class="has-text-weight-bold"><%= @daily_tasks.count %></span> <span class="has-text-weight-bold has-text-warning">tasks</span> due today.</p>
        </div>
        <%= link_to "View", daily_tasks_path, class: "button is-primary" %>
      </div>
    <% else %>
      <%= render partial: "daily_tasks/no_tasks"  %>
    <% end %>

  </section>
<% end %>

app/views/dashboard/new_goal.html.erb
<%= turbo_frame_tag "new_goal_frame" do %>
  <section class="section">
    <%= form_with model: @smart_goal, url: :dashboard_create_goal, class: "form" do |f| %>

      <div class="is-flex">
        <div class="field mr-4">
          <%= f.label :track, class: "label" %>
          <div class="select">
            <%= f.select :user_track_id, options_for_select(@tracks) %>
          </div>
        </div>

        <div class="field mr-4">
          <%= f.label :start_date, class: "label" %>
          <%= f.date_field :start_date, value: Date.today, class: "input" %>
        </div>

        <div class="field mr-4">
          <%= f.label :end_date, class: "label" %>
          <%= f.date_field :end_date, value: Date.today + 30.days, class: "input" %>
        </div>
      </div>

      <div class="field">
        <%= f.label "Measurable goal:", class: "label" %>
        <%= f.text_field :measurable_goal, class: "input" %>
      </div>

      <%= f.submit "Save", class: "button is-primary" %>
    <% end %>
  </section>
<% end %>

<%= render partial: "layouts/error_messages", locals: { messages: [] } %>

app/views/dashboard/new_workout.html.erb
<section class="hero">
  <div class="hero-body">
    <h1 class="title has-text-primary">Let's add a workout</h1>
    <h2 class="subtitle has-text-warning">To proceed, fill out the form below</h2>
  </div>
</section>

<section class="section">
  <%= turbo_frame_tag "gym_lift" do %>
    <%= form_with model: @workout, url: :dashboard_create_workout do |f| %>
      <div class="field">
        <%= f.label "Date:", class: "label" %>
        <div class="select">
          <%= f.select :date, options_from_collection_for_select(@last_two_weeks, :to_s, :to_s) %>
        </div>
      </div>

      <div class="field">
        <%= f.label "Type:", class: "label" %>
        <div class="select">
          <%= f.select :workout_type, options_for_select(Workout.workout_types.map{ |k, v| [k.capitalize, v]}) %>
        </div>
      </div>

      <%= button_tag "Add Lift", formaction: dashboard_add_lift_to_workout_path, formmethod: :post, data: { turbo_stream: true }, class: "button is-warning" %>
      <%#= f.submit "Continue", class: "button is-primary" %>
      <%#= turbo_frame_tag "workout_lift_form_frame" do %>

      <%# end %>
    <% end %>
  <% end %>
</section>

app/views/dashboard/saga.html.erb
<section class="hero is-small">
  <div class="hero-body">
    <h1 class="barlow-condensed-bold is-size-2"><%= @saga.title %></h1>
  </div>
</section>

<section class="section">
  <h2 class="barlow-condensed-semibold is-size-4">Content: </h2>
  <div class="content">
    <%= @saga.content.html_safe %>
  </div>
</section>