config/routes.rb
Rails.application.routes.draw do
  get "tracks/index"
  get "tracks/new"
  get "tracks/create"
  get "tracks/update"
  get "tracks/edit"
  get "tracks/delete"
  get "daily_tasks/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # Auth:
  root "auth#log_in"
  get "auth/sign_up"
  post "auth/sign_user_up", as: "sign_user_up"
  post "auth/log_user_in", as: "log_user_in"
  get "dashboard/home"
  get "dashboard/new_goal"
  post "dashboard/create_goal"
  # Resources:
  resources :workouts do
    post "add_lift_form", on: :collection, as: :add_lift_form
    delete "delete_lift_form", on: :collection, as: :delete_lift_form
    get "list", on: :collection
    post "add_lift_to_workout", on: :member
  end
  resources :daily_tasks do
    post "add_task", on: :collection, as: :add_task
    post "add_task_to_box", on: :collection, as: :add_task_to_box
    patch "complete", on: :member, as: :complete
  end
  resources :sagas, only: [ :index, :new, :create, :show, :edit, :update, :destroy ]
  resources :smart_goals do
    patch "complete", on: :member, as: :complete
  end
  resources :tracks
end

app/models/workout.rb
class Workout < ApplicationRecord
  has_many :gym_lifts, dependent: :destroy
  belongs_to :user
  enum workout_type: { push: 0, pull: 1, legs: 2, cardio: 3 }
  accepts_nested_attributes_for :gym_lifts,
                                reject_if: :all_blank, allow_destroy: true
  validates :gym_lifts, { length: { minimum: 1 } }
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  include Authentication
  before_action :check_logged_in
  def index
    @user = User.find(session[:user_id])
    @workout = @user.workouts&.last
  end

  def new
    @workout = Workout.new
    @workout.gym_lifts.build
    @last_two_weeks = (Date.today - 14..Date.today).to_a
    @workout_types = Workout.workout_types
    @all_exercises = Exercise.all.select(:id, :title).order("title ASC")
  end

  def add_lift_form
    @all_exercises = Exercise.all.select(:id, :title).order("title ASC")
    @frame_id = SecureRandom.uuid
  end
  def delete_lift_form
    @frame_id = params[:frame_id]
    @workout = Workout.find_by(id: params[:workout_id])
    @gym_lift = GymLift.find_by(id: @frame_id)
    if @workout.present?
      if @workout.gym_lifts.count > 1
        @gym_lift.destroy
        render turbo_stream: turbo_stream.remove(@frame_id)
      else
        render turbo_stream: turbo_stream.replace("err_messages", partial: "error_messages", locals: { messages: [ "ERROR: A workout must have at least one lift" ] })
      end
    else
      render turbo_stream: turbo_stream.remove(@frame_id)
    end
  end

  def edit
    @workout = Workout.find(params[:id])
    @user = User.find(session[:user_id])
    @last_two_weeks = (Date.today - 14..Date.today).to_a
    @workout_types = Workout.workout_types
    @all_exercises = Exercise.all.select(:id, :title).order("title ASC")
  end

  def create
    workout = Workout.new(workout_params)
    workout.user_id = session[:user_id]
    if workout.errors.any?
      render turbo_stream: turbo_stream.replace("err_messages", partial: "error_messages", locals: { messages: workout.errors.full_messages })
    end
    workout.save!
  rescue
    render turbo_stream: turbo_stream.replace("err_messages", partial: "error_messages", locals: { messages: [ "There's been an error. Please try again." ] })
  end
  def list
    @user = User.find(session[:user_id])
    @workouts = @user.workouts.all
  end
  def update
    @workout = Workout.find(params[:id])
    @workout.update(workout_params)
    if @workout.errors.any?
      render turbo_stream: turbo_stream.replace("err_messages", partial: "error_messages", locals: { messages: @workout.errors.full_messages })
    end
  rescue
    render turbo_stream: turbo_stream.replace("err_messages", partial: "error_messages", locals: { messages: [ "There's been an error. Please try again." ] })
  end
  def destroy
    @user = User.find(session[:user_id])
    @workout = Workout.find(params[:id])
    @workout.destroy
  end

  def add_lift_to_workout
    @workout = Workout.find(params[:id])
    @all_exercises = Exercise.all.select(:id, :title).order("title ASC")
    gym_lift = GymLift.create(workout: @workout, exercise: Exercise.first)
    if gym_lift.errors.any?
      render turbo_stream: turbo_stream.replace("err_messages", partial: "err_messages", locals: { messages: gym_lift.errors.full_messages })
    end
    @frame_id = gym_lift.id
  rescue
    render turbo_stream: turbo_stream.replace("err_messages", partial: "err_messages", locals: { messages: [ "There's been an error." ] })
  end

  private

  def workout_params
    params.require(:workout).permit([ :created_at, :workout_type, gym_lifts_attributes: [ :id, :exercise_id, :reps, :sets, :weight ] ])
  end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
  def gym_lift_dom_id(workout)
    if workout.present?
      p "Loading..."
    end
  end
end

app/views/workouts/_add_lift_form.html.erb
<%= turbo_frame_tag @frame_id, class: "my-4" do %>
  <%= fields_for "workout[gym_lifts_attributes][]", GymLift.new, index: SecureRandom.random_number(100) do |ff| %>
    <%= hidden_field_tag "frame_id_#{@frame_id}", @frame_id %>
    <div class="block">
      <div class="columns">
        <div class="column is-one-fifth">
          <%= ff.label "Lift:", class: "label"  %>
          <div class="select">
            <%= ff.select :exercise_id, options_from_collection_for_select(@all_exercises, :id, :title) %>
          </div>
        </div>

        <div class="column is-one-fifth">
          <%= ff.label "Reps:", class: "label" %>
          <%= ff.number_field :reps, class: "input" %>
        </div>

        <div class="column is-one-fifth">
          <%= ff.label "Sets:", class: "label" %>
          <%= ff.number_field :sets, class: "input" %>
        </div>



        <div class="column is-one-fifth">
          <%= ff.label "Weight:", class: "label" %>
          <%= ff.number_field :weight, class: "input" %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="block">
    <%= link_to "Delete", delete_lift_form_workouts_path(frame_id: @frame_id), data: { "turbo-method": :delete }, class: "button is-danger" %>
  </div>
<% end %>

app/views/workouts/_helper_javascript.html.erb
<script type="text/javascript">
    let isRequestInProgress = false;

    // Before sending the request, disable the button
    document.addEventListener('turbo:before-fetch-request', function(event) {
        const button = event.target.querySelector('button');
        if (button && !isRequestInProgress) {
            button.disabled = true;
            isRequestInProgress = true; // Lock it while the request is in progress
        }
    });

    // After the frame updates (append), re-enable the button
    document.addEventListener('turbo:frame-load', function(event) {
        const button = event.target.querySelector('button');
        if (button) {
            button.disabled = false;
        }
        isRequestInProgress = false; // Unlock it when the request completes
    });

    document.addEventListener('DOMContentLoaded', () => {
        // Functions to open and close a modal
        function openModal($el) {
            $el.classList.add('is-active');
        }

        function closeModal($el) {
            $el.classList.remove('is-active');
        }

        function closeAllModals() {
            (document.querySelectorAll('.modal') || []).forEach(($modal) => {
                closeModal($modal);
            });
        }

        // Add a click event on buttons to open a specific modal
        (document.querySelectorAll('.js-modal-trigger') || []).forEach(($trigger) => {
            const modal = $trigger.dataset.target;
            const $target = document.getElementById(modal);

            $trigger.addEventListener('click', () => {
                openModal($target);
            });
        });

        // Add a click event on various child elements to close the parent modal
        (document.querySelectorAll('.modal-background, .modal-close, .modal-card-head .delete, .modal-card-foot .button') || []).forEach(($close) => {
            const $target = $close.closest('.modal');

            $close.addEventListener('click', () => {
                closeModal($target);
            });
        });

        // Add a keyboard event to close all modals
        document.addEventListener('keydown', (event) => {
            if(event.key === "Escape") {
                closeAllModals();
            }
        });
    });
    function openModal(modalId) {
        let element = document.getElementById(modalId);
        element.classList.add("is-active");
    }
    function addLift(e) {
        e.preventDefault();
        openModal("add-lift-modal");
    }
</script>

app/views/workouts/add_lift_form.turbo_stream.erb
<%= turbo_stream.append "workout_lifts" do %>
  <%= render partial: "add_lift_form" %>
<% end %>

app/views/workouts/add_lift_to_workout.turbo_stream.erb
<%= turbo_stream.append("workout_lifts") do %>
  <%= render partial: "add_lift_form", locals: { frame_id: @frame_id } %>
<% end %>

app/views/workouts/create.turbo_stream.erb
<%= turbo_stream.replace("gym_lift") do %>
  <%= render partial: "success_message", locals: { message: "Workout successfully created." }  %>
<% end %>

app/views/workouts/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@workout) %>
<% if @user.workouts.count.zero? %>
  <%= turbo_stream.replace "list_workouts" do %>
    <div>No workouts. Please add more! </div>
  <% end %>
<% end %>

app/views/workouts/edit.html.erb
<%= turbo_page_requires_reload %>
<section class="hero is-small">
  <div class="hero-body">
    <h1 class="title barlow-condensed-bold is-size-2">Editing <span class="has-text-warning"><%= @workout.created_at.strftime("%m/%d/%Y") %></span></h1>
  </div>
</section>
<section class="section">
  <%= turbo_frame_tag "gym_lifts" do %>
    <%= form_with model: @workout, method: :patch do |f| %>
      <div class="columns is-vcentered">
        <div class="column is-one-fifth is-flex">
          <%= f.label "Date:", class: "label my-auto" %>
          <div class="select my-auto ml-2">
            <%= f.select :created_at, options_from_collection_for_select(@last_two_weeks, :to_s, :to_s) %>
          </div>
        </div>
        <div class="column is-one-fifth is-flex">
          <%= f.label "Type:", class: "label my-auto" %>
          <div class="select my-auto ml-2">
            <%= f.select :workout_type, options_for_select(@workout_types.map{ |k, v| [k.capitalize, k]}) %>
          </div>
        </div>
        <div class="column is-flex">
          <%= button_tag "Add Lift", formaction: add_lift_to_workout_workout_path, formmethod: :post, data: { turbo_stream: true }, class: "button is-warning my-auto ml-auto" %>
          <%= f.submit "Continue", class: "button is-primary ml-2" %>
        </div>
      </div>

      <% @workout.gym_lifts.each do |lift| %>
        <%= turbo_frame_tag lift.id do %>
          <%= f.fields_for lift do |ff| %>
            <div class="block">
              <div class="columns">
                <div class="column is-one-fifth">
                  <%= ff.label "Lift:", class: "label"  %>
                  <div class="select">
                    <%= ff.select :exercise_id, options_from_collection_for_select(@all_exercises, :id, :title) %>
                  </div>
                </div>

                <div class="column is-one-fifth">
                  <%= ff.label "Reps:", class: "label" %>
                  <%= ff.number_field :reps, class: "input" %>
                </div>

                <div class="column is-one-fifth">
                  <%= ff.label "Sets:", class: "label" %>
                  <%= ff.number_field :sets, class: "input" %>
                </div>

                <div class="column is-one-fifth">
                  <%= ff.label "Weight:", class: "label" %>
                  <%= ff.number_field :weight, class: "input" %>
                </div>
              </div>
            </div>
          <% end %>
          <%= link_to "Delete", delete_lift_form_workouts_path(frame_id: lift.id, workout_id: @workout.id), data: { "turbo_method": :delete }, class: "button is-danger" %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>

  <%= turbo_frame_tag "workout_lifts" do %>

  <% end %>

</section>

<%= render partial: "error_messages", locals: { messages: [] } %>

app/views/workouts/index.html.erb
<%= turbo_page_requires_reload %>
<section class="section">
  <h1 class="title is-size-2 barlow-condensed-bold">Welcome to your fitness dashboard, <span class="has-text-primary"><%= @user.first_name.split(" ")[0] %>!</span></h1>
  <span class="subtitle is-size-5">From here, you can view <span class="has-text-primary">your progress</span>, <span class="has-text-warning">workouts</span>, and <span class="has-text-danger">more!</span></span>
</section>
<section class="section">
  <span class="barlow-condensed-bold is-size-2">Progress:</span>
  <progress class="progress is-primary" value="<%= @user.workouts.count %>" max="100"></progress>
  <span class="is-size-5">Total: <span class="has-text-primary has-text-weight-bold"><%= @user.workouts.count %> workouts</span>.</span>
  <br>
  <span class="is-size-5">Current streak: <span class="has-text-weight-bold has-text-warning"><%= @user.workout_streak %> days</span>.</span>
  <br>
</section>


<section class="section">
  <%= link_to "Add a workout", new_workout_path, class: "button is-primary" %>
  <% if @user.workouts.present? %>
    <%= link_to "List workouts", list_workouts_path, class: "button is-warning" %>
  <% end %>
</section>

app/views/workouts/list.html.erb
<section class="hero is-small">
  <div class="hero-body">
    <h1 class="title barlow-condensed-bold is-size-2">
      Here's all your workouts, <span class="has-text-warning"><%= @user.first_name %></span>.
    </h1>
  </div>
</section>
<section class="section">
  <%= turbo_frame_tag "list_workouts" do %>
    <div class="fixed-grid has-3-cols">
      <div class="grid">
        <% @workouts.includes(:gym_lifts).each do |workout| %>
          <% gym_lifts = workout.gym_lifts %>
          <%= turbo_frame_tag dom_id(workout) do %>
            <div class="cell">
              <div class="card">
                <header class="card-header">
                  <p class="card-header-title is-size-3 barlow-condensed-bold">
                    <%= workout.created_at.strftime("%m/%d/%Y") %>
                  </p>
                </header>
                <div class="card-content">
                  <div class="is-flex is-flex-direction-column">
                    <span class="">Type: <span class="has-text-warning"><%= workout.workout_type.humanize %></span></span>
                    <span class="">Lifts: <span class="has-text-danger"><%= workout.gym_lifts.count %></span></span>
                  </div>
                </div>
                <footer class="card-footer">
                  <%= link_to "Edit", edit_workout_path(workout.id), class: "card-footer-item" %>
                  <%= link_to "Delete", workout_path(workout.id), data: { "turbo-method": :delete }, class: "card-footer-item" %>
                </footer>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
  <% if @user.workouts.count.zero? %>
    <div>No workouts. Please add more! </div>
  <% end %>
</section>

app/views/workouts/new.html.erb
<section class="hero is-small">
  <div class="hero-body">
    <h1 class="title barlow-condensed-bold is-size-2">Let's add a <span class="has-text-warning">workout</span></h1>
    <h2 class="subtitle is-size-5">To proceed, fill out the form below</h2>
  </div>
</section>

<section class="section">
  <%= turbo_frame_tag "gym_lift" do %>
    <%= form_with model: @workout do |f| %>
      <div class="columns is-vcentered">
        <div class="column is-one-fifth is-flex">
          <%= f.label "Date:", class: "label my-auto" %>
          <div class="select my-auto ml-2">
            <%= f.select :created_at, options_from_collection_for_select(@last_two_weeks, :to_s, :to_s) %>
          </div>
        </div>
        <div class="column is-one-fifth is-flex">
          <%= f.label "Type:", class: "label my-auto" %>
          <div class="select my-auto ml-2">
            <%= f.select :workout_type, options_for_select(@workout_types.map{ |k, v| [k.capitalize, k]}) %>
          </div>
        </div>
        <div class="column is-flex">
          <%= button_tag "Add Lift", formaction: add_lift_form_workouts_path, formmethod: :post, data: { turbo_stream: true }, class: "button is-warning my-auto ml-auto" %>
          <%= f.submit "Continue", class: "button is-primary ml-2" %>
        </div>
      </div>

      <div class="field">
        <%= f.fields_for :gym_lifts do |ff| %>
          <div class="block">
            <div class="columns">
              <div class="column is-one-fifth">
                <%= ff.label "Lift:", class: "label"  %>
                <div class="select">
                  <%= ff.select :exercise_id, options_from_collection_for_select(@all_exercises, :id, :title) %>
                </div>
              </div>

              <div class="column is-one-fifth">
                <%= ff.label "Reps:", class: "label" %>
                <%= ff.number_field :reps, class: "input" %>
              </div>

              <div class="column is-one-fifth">
                <%= ff.label "Sets:", class: "label" %>
                <%= ff.number_field :sets, class: "input" %>
              </div>

              <div class="column is-one-fifth">
                <%= ff.label "Weight:", class: "label" %>
                <%= ff.number_field :weight, class: "input" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <%= turbo_frame_tag "workout_lifts" do %>

      <% end %>
    <% end %>
  <% end %>
</section>
<%= render partial: "error_messages", locals: { messages: [] } %>

app/views/workouts/update.turbo_stream.erb
<%= turbo_stream.replace "gym_lifts" do %>
  <%= render partial: "success_message", locals: { message: "Workout successfully edited." } %>
<% end %>
<%= turbo_stream.replace "workout_lifts" do %>
  <div></div>
<% end %>