config/routes.rb
Rails.application.routes.draw do
  get "tracks/index"
  get "tracks/new"
  get "tracks/create"
  get "tracks/update"
  get "tracks/edit"
  get "tracks/delete"
  get "daily_tasks/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # Auth:
  root "auth#log_in"
  get "auth/sign_up"
  post "auth/sign_user_up", as: "sign_user_up"
  post "auth/log_user_in", as: "log_user_in"
  get "dashboard/home"
  get "dashboard/new_goal"
  post "dashboard/create_goal"
  # Resources:
  resources :workouts do
    post "add_lift_form", on: :collection, as: :add_lift_form
    delete "delete_lift_form", on: :collection, as: :delete_lift_form
    get "list", on: :collection
    post "add_lift_to_workout", on: :member
  end
  resources :daily_tasks do
    post "add_task", on: :collection, as: :add_task
    post "add_task_to_box", on: :collection, as: :add_task_to_box
    patch "complete", on: :member, as: :complete
  end
  resources :sagas, only: [ :index, :new, :create, :show, :edit, :update, :destroy ]
  resources :smart_goals do
    patch "complete", on: :member, as: :complete
  end
  resources :tracks
end

app/views/layouts/_bottom_navbar.html.erb
<nav class="navbar is-fixed-bottom" role="navigation" aria-label="main navigation">
  <div class="navbar-menu">
    <div class="navbar-end">
      <% if session[:page_type] == "tracks" %>
        <div class="navbar-item">
          <button type="button" data-controller="modals" data-action="modals#open_modal" data-modals-modal-id-value="<%= dom_id(Track.new) %>" class="button is-primary">
            New track
            <i class="fa fa-solid fa-plus ml-2"></i>
          </button>
        </div>
      <% elsif session[:page_type] == "smart_goals" %>
        <div class="navbar-item">
          <button type="button" data-controller="modals" data-action="modals#open_modal" data-modals-modal-id-value="<%= dom_id(SmartGoal.new) %>" class="button is-primary">
            New goal
            <i class="fa fa-solid fa-plus ml-2"></i>
          </button>
        </div>
      <% elsif session[:page_type] == "sagas" %>
        <div class="navbar-item">
          <a href="<%= new_saga_path %>" class="button is-primary">
            New saga <i class="fa fa-solid fa-plus ml-2"></i>
          </a>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_error_messages.html.erb
<%= turbo_frame_tag "err_messages" do %>
  <div class="">
    <% messages&.each_with_index do |message, index| %>
      <div id="delete_msg_<%= index %>" class="notification animate__animated animate__fadeIn is-danger">
        <button type=button class="delete" onclick="deleteMessageComponent('delete_msg_<%= index %>');"></button>
        <%= message %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_main_navbar.html.erb
<% if %w(dashboard tracks smart_goals sagas daily_tasks).include?session[:page_type] %>
  <header class="container is-fluid p-5">
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <div class="navbar-item">
          <span class="title barlow-condensed-bold has-text-primary">PowerUser</span>
        </div>
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="poweruser_navbar">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="poweruser_navbar" class="navbar-menu">
        <div class="navbar-start">
          <%= link_to "Dashboard", dashboard_home_path, class: "navbar-item" %>
          <%= link_to "Sagas", sagas_path, class: "navbar-item" %>
          <%= link_to "Goals", smart_goals_path, class: "navbar-item" %>
          <%= link_to "Tasks", daily_tasks_path, class: "navbar-item" %>
          <%= link_to "Tracks", tracks_path, class: "navbar-item" %>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <span id="pomodoro_time" class="has-text-primary has-text-weight-bold"></span>
            <button id="start_pomo" onclick="startPomodoroTimer();" class="button is-primary">Start</button>
            <button id="stop_pomo" onclick="stopPomodoroTimer();" class="button is-danger">Stop</button>
          </div>
          <div class="navbar-item">
            <%= link_to "Log out", root_path, class: "button is-light", data: { turbo_prefetch: false } %>
          </div>
        </div>
      </div>
    </nav>
  </header>
<% else %>
  <header class="container is-fluid p-5">
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <div class="navbar-item">
          <span class="title barlow-condensed-bold">Welcome to <span class="has-text-primary">PowerUser</span></span>
        </div>
      </div>

      <div id="poweruser_navbar" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <% if session[:page_type] == "sign_up" %>
              <%= link_to "Log in", root_path, class: "button is-warning", data: { turbo_prefetch: false } %>
            <% else %>
              <%= link_to "Sign up", auth_sign_up_path, class: "button is-warning", data: { turbo_prefetch: false } %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
  </header>
<% end %>
<%= javascript_include_tag "pomodoro" %>

app/views/layouts/_success_message.html.erb
<section class="section">
  <div class="title barlow-condensed-bold is-4 has-text-primary">
    <p>Success!</p>
  </div>
  <div class="block">
    <%= message %>
  </div>
  <%= link_to "Go back", workouts_path, class: "button is-warning" %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Poweruser" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <%= javascript_importmap_tags %>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css"
    >
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <%= javascript_include_tag "bulma_helper_javascript" %>
    <script src="https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.snow.css" rel="stylesheet">
  </head>

  <body class="montserrat-400">
    <%= render partial: "layouts/main_navbar" %>
    <section class="">
      <%= yield %>
    </section>
    <%= render partial: "layouts/bottom_navbar" %>
  </body>
</html>